{
 "title": "CodeSwarm — .Ubuntu Host",
 "tags": [
  "adopted",
  "codeswarm",
  "logging"
 ],
 "time": { "from": "2026-02-16T23:46:42.174Z", "to": "2026-02-17T00:46:42.174Z" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Usage % (instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sprint3:host_cpu_usage_percent" }
   ]
  },
  {
   "title": "Memory Usage % (instance)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sprint3:host_memory_usage_percent"
    }
   ]
  },
  {
   "title": "Disk Usage % (mountpoint)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sprint3:host_disk_usage_percent"
    }
   ]
  },
  {
   "title": "Docker Errors",
   "type": "logs",
   "gridPos": { "h": 11, "w": 21, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{env=\"sandbox\", log_source=\"docker\"} |= `` | level != `info`"
    }
   ]
  }
 ]
}